### PR TITLE
Finalise Create Vote Process

### LINKED ISSUE #7: vote not working
function has been left unfinished

### PR DESCRIPTION
**Pull request by alexbarnsley**
Added functionality to vote for a delegate, and also remove a vote.

Resolves #7

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -396,20 +400,53 @@ vorpal
...
-          message: 'Sending '+arkamount/100000000+'ARK '+(currency?'('+currency+args.amount+') ':'')+'to '+args.recipient+' now',
-        }, function(result){
-          if (result.continue) {
-            return seriesCb(null, transaction);
-          }
-          else {
-            return seriesCb("Aborted.")
-          }
-        });
+        if (args.name === undefined) {
```
Comment (fix) [inline index.js]: this makes nonsense to derive the publickey of the votes from the passphrase (ie you would need to ask passphrase for the delegate you vote for...) I would remove this condition and suppose there is always a name.

Comment (fix) [reply index.js]: ok i am wrong, you are getting existing vote and remove it.

I would then change this way:
- `account unvote` -> remove vote if any
- `account vote <name>` -> vote for `name` and remove vote beforehand if any.

Comment (alexbarnsley) [reply index.js]: Okay. Just to clarify, you just want me to tweak the "new vote" process, to un-vote the previous if applicable. You also want me to create a separate "command" which will be to unvote, if any.

Could you confirm that there can only ever be 1 vote per account please, or whether I should cater for removing all votes just in case?

Thanks!

Comment (fix) [reply index.js]: Yes there can be only 1 vote per account (unlike lisk for instance where there can be 101 votes per account)

Comment (alexbarnsley) [reply index.js]: Okay, I will only cater for 1 vote.
When unvoting before creating a new vote, do you think it's worth waiting for the transaction to confirm? I was thinking of a standard setInterval to check every 5 seconds to see if the unvote transaction has confirmed. Does that sound acceptable?
I'm almost done implementing your suggested changes

**Comment by alexbarnsley** [comment]
@fix I have address your comments if you could take a look please. Diff is quite drastic so maybe worth a test?

thanks

File: index.js [hunk 2]
```diff
@@ -395,20 +399,148 @@ vorpal
         });
       },
       function(passphrase, seriesCb){
-        var delegate = args.name;
-        var transaction = arkjs.delegates.createVote(passphrase);
+        var delegateName = args.name;
+        arkjs.crypto.setNetworkVersion(30);
```
Comment (fix) [inline index.js]: no here you should use `arkjs.crypto.setNetworkVersion(network.config.version);` instead

File: index.js [hunk 3]
```diff
@@ -395,20 +399,148 @@ vorpal
...
           }
-          else {
-            return seriesCb("Aborted.")
+          else{
+            return seriesCb("Aborted.");
+          }
+        });
+      },
+      function(passphrase, seriesCb){
+        arkjs.crypto.setNetworkVersion(30);
```
Comment (fix) [inline index.js]: arkjs.crypto.setNetworkVersion(network.config.version);

**Comment by fix** [comment]
sounds great now!

+5

**Comment by alexbarnsley** [comment]
Thanks @fix!
